import React from 'react'

const Itmes = () => {
    const data = [
    {
  "login": "Asiyaa22",
  "id": 136359347,
  "node_id": "U_kgDOCCCtsw",
  "avatar_url": "https://avatars.githubusercontent.com/u/136359347?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Asiyaa22",
  "html_url": "https://github.com/Asiyaa22",
  "followers_url": "https://api.github.com/users/Asiyaa22/followers",
  "following_url": "https://api.github.com/users/Asiyaa22/following{/other_user}",
  "gists_url": "https://api.github.com/users/Asiyaa22/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Asiyaa22/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Asiyaa22/subscriptions",
  "organizations_url": "https://api.github.com/users/Asiyaa22/orgs",
  "repos_url": "https://api.github.com/users/Asiyaa22/repos",
  "events_url": "https://api.github.com/users/Asiyaa22/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Asiyaa22/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Asiya Farhath",
  "company": null,
  "blog": "",
  "location": "Hyderabad, India",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "asiyahiba",
  "public_repos": 52,
  "public_gists": 0,
  "followers": 7,
  "following": 8,
  "created_at": "2023-06-12T15:50:01Z",
  "updated_at": "2025-03-27T07:17:36Z"
},{
  "login": "Tushar-Shinde31",
  "id": 140314810,
  "node_id": "U_kgDOCF0Iug",
  "avatar_url": "https://avatars.githubusercontent.com/u/140314810?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Tushar-Shinde31",
  "html_url": "https://github.com/Tushar-Shinde31",
  "followers_url": "https://api.github.com/users/Tushar-Shinde31/followers",
  "following_url": "https://api.github.com/users/Tushar-Shinde31/following{/other_user}",
  "gists_url": "https://api.github.com/users/Tushar-Shinde31/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Tushar-Shinde31/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Tushar-Shinde31/subscriptions",
  "organizations_url": "https://api.github.com/users/Tushar-Shinde31/orgs",
  "repos_url": "https://api.github.com/users/Tushar-Shinde31/repos",
  "events_url": "https://api.github.com/users/Tushar-Shinde31/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Tushar-Shinde31/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "TUSHAR SHINDE ",
  "company": null,
  "blog": "https://portfolio-tush.vercel.app/",
  "location": "Maharashtra, India",
  "email": null,
  "hireable": null,
  "bio": "I love building things :)",
  "twitter_username": "tushaarizz",
  "public_repos": 56,
  "public_gists": 0,
  "followers": 15,
  "following": 4,
  "created_at": "2023-07-23T10:27:30Z",
  "updated_at": "2025-07-26T07:03:27Z"
},
{
  "login": "Shabbirjodhpur",
  "id": 62835725,
  "node_id": "MDQ6VXNlcjYyODM1NzI1",
  "avatar_url": "https://avatars.githubusercontent.com/u/62835725?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/Shabbirjodhpur",
  "html_url": "https://github.com/Shabbirjodhpur",
  "followers_url": "https://api.github.com/users/Shabbirjodhpur/followers",
  "following_url": "https://api.github.com/users/Shabbirjodhpur/following{/other_user}",
  "gists_url": "https://api.github.com/users/Shabbirjodhpur/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/Shabbirjodhpur/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/Shabbirjodhpur/subscriptions",
  "organizations_url": "https://api.github.com/users/Shabbirjodhpur/orgs",
  "repos_url": "https://api.github.com/users/Shabbirjodhpur/repos",
  "events_url": "https://api.github.com/users/Shabbirjodhpur/events{/privacy}",
  "received_events_url": "https://api.github.com/users/Shabbirjodhpur/received_events",
  "type": "User",
  "user_view_type": "public",
  "site_admin": false,
  "name": "Shabbir Jodhpur",
  "company": "www.fyi.is | www.thehackingschool.com | www.msbinstitute.com | www.codeforindia.com",
  "blog": "shabbir.tech",
  "location": "Hyderabad, India",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "shabbirjodhpur",
  "public_repos": 65,
  "public_gists": 6,
  "followers": 29,
  "following": 45,
  "created_at": "2020-03-29T11:09:51Z",
  "updated_at": "2025-09-17T05:57:12Z"
}
 ];
  return (
    <div>
        name
        username
        url
    </div>
  )
}

export default Itmes